### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by ForgivenNin** [RadicalAjay/SHA3#1]
Hello,

I have recently been trying to come up with a system that will likely involve hashing, and while I don't know which language I would like to make it in, if I chose Python3, I wanted to know how to use this from the command line. I know it uses a class, but I have never been able to wrap my mind around how classes work.

**Comment by ForgivenNin** [comment]
Upon further inspection, I did find that you had some runs in the bottom of the script, but I realized that there may not be a way to decrypt the hash unless there is something I have not yet seen.

**Comment by RadicalAjay** [comment]
Yeah, we cannot decrypt or unhash a hashed digest. If you want to use this from the command line, import sys and then take the input as sys.argv[1] and hash it. You can do this by `sha._hash(sys.argv[1])` after instantiating sha as an object of the class.
